# Generated by Django 5.1.6 on 2025-11-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(error_messages={'blank': "Iltimos, ushbu maydonni to'ldiring.", 'null': "Ushbu maydon bo'sh bo'la olmaydi."}, max_length=50),
        ),
    ]
