# Generated by Django 5.1.6 on 2025-11-20 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vazifa ', 'verbose_name_plural': 'Vazifalar'},
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('completed', False)), fields=('title',), name='unique_title_when_not_completed'),
        ),
    ]
