# Generated by Django 5.1.6 on 2025-11-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_title_when_not_completed',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
